env_params:
  board_size: 9     # 宽和高
  action_size: 82   # 动作空间大小，对于围棋是 board_size * board_size+1
  in_channels: 3    # 神经网络输入平面的通道数：黑棋平面、白棋平面、当前颜色平面

mcts_params:
  num_simulations: 400   # MCTS每次搜索进行的模拟次数
  c_puct: 1.5            # PUCT探索常数，控制利用和探索的折中
  

network_params:
  num_residual_blocks: 5  # 残差块的数量，控制模型深度
  num_channels: 64        # 每个卷积层的通道数量，控制模型宽度

train_params:
  batch_size: 256               # SGD 每次迭代用于梯度计算的批大小
  learning_rate: 0.002          # 动量 SGD 的基础学习率
  num_epochs: 10                # 每次搜集完自对弈数据后，对经验回放池抽样训练的 Epoch 数
  eval_win_rate_threshold: 0.55 # 模型更替胜率阈值
  replay_buffer_size: 100000    # 经验回放池容量，保存过去的样本对
