env_params:
  board_size: 9
  action_size: 82
  in_channels: 9
  komi: 6.5
  max_moves: 180

mcts_params:
  num_simulations: 1600
  c_puct: 1.5
  dirichlet_epsilon: 0.25
  dirichlet_alpha: 0.13
  temperature_threshold: 30
  virtual_loss_batch_size: 8

network_params:
  num_residual_blocks: 5
  num_channels: 64

train_params:
  batch_size: 256
  learning_rate: 0.1
  momentum: 0.9
  num_epochs: 2
  eval_win_rate_threshold: 0.55
  replay_buffer_size: 500000
  render_interval: 10
  weight_decay: 0.0001
  initial_population: 300
  num_iterations: 20
  num_games_per_iteration: 200
  num_eval_games: 40